version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    # ports:
    #  - "9200:9200"
    #  - "9300:9300"
    volumes:
    - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    - elasticsearch:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
      # Force publishing on the 'elk' overlay.
      network.publish_host: _eth0_
    networks:
    - basedosdados

  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.2
    # ports:
    #   - "5044:5044"
    #   - "5001:5001/tcp"
    #   - "5001:5001/udp"
    #   - "9600:9600"
    volumes:
    - ./logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    container_name: logstash
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    networks:
    - basedosdados

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    ports:
      - "5601:5601"
    volumes:
    - ./kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      - elasticsearch
    networks:
    - basedosdados


volumes:
  elasticsearch:

networks:
  basedosdados:
    external:
      name: basedosdados
