version: '3'
services:
  wordpress:
    ports:
      - 8080:80
    volumes:
      - wordpress-html:/var/www/html

  wordpress-db:
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress-html:
  db:
