version: '3'
services:
  wordpress:
    volumes:
      - ./wordpress-html:/var/www/html
    ports:
    - 2:80
    networks:
    - basedosdados

  wordpress-db:
    volumes:
      - ./db:/var/lib/mysql
    networks:
    - basedosdados


volumes:
  wordpress:
  db:

networks:
  basedosdados:
    external:
      name: basedosdados
