scheming_version: 1
dataset_type: dataset
about: Schema para Base dos Dados
about_url: http://github.com/ckan/ckanext-scheming
dataset_fields:
  - field_name: title
    label: Título
    preset: title
    form_placeholder: 'ex.: Um título descritivo'
    required: 'true'
  - field_name: name
    label: URL
    preset: dataset_slug
    form_placeholder: eg. dataset
    required: 'true'
  - field_name: notes
    label: Descrição
    form_snippet: markdown.html
    form_placeholder: 'ex.: Descrição e anotações úteis sobre os dados.'
  - field_name: tag_string
    label: Etiquetas
    preset: tag_string_autocomplete
    form_placeholder: 'ex.: fertilidade, preço, desmatamento'
    required: 'true'
  - field_name: owner_org
    label: Organization
    preset: dataset_organization
    required: 'true'
  - field_name: regiao
    label: Região
    required: 'true'
    preset: select
    choices:
    - value: vazio
      label: " "
    - value: internacional
      label: Internacional
    - value: america_sul
      label: América do Sul
    - value: africa
      label: África
    - value: america_central
      label: América Central
    - value: america_norte
      label: América do Norte
    - value: asia
      label: Ásia
    - value: europa
      label: Europa
    - value: oceania
      label: Oceania
    - value: oriente_medio
      label: Oriente Médio
    - value: antartica
      label: Antártica
  - field_name: pais
    label: País
    required: 'true'
    help_text: Para bases de país único.
    preset: select
    choices:
    - value: vazio
      label: " "
    - value: brasil
      label: Brasil
    - value: africa-sul
      label: África do Sul
    - value: argentina
      label: Argentina
    - value: bolivia
      label: Bolívia
    - value: australia
      label: Austrália
    - value: canada
      label: Canadá
    - value: chile
      label: Chile
    - value: china
      label: China
    - value: colombia
      label: Colômbia
    - value: espanha
      label: Espanha
    - value: EUA
      label: Estados Unidos
    - value: franca
      label: França
    - value: india
      label: Índia
    - value: indonesia
      label: Indonésia
    - value: inglaterra
      label: Inglaterra
    - value: japao
      label: Japão
    - value: malasia
      label: Malásia
    - value: mexico
      label: México
    - value: peru
      label: Peru
    - value: portugal
      label: Portugal
    - value: russia
      label: Rússia
    - value: uruguai
      label: Uruguai
    - value: venezuela
      label: Venezuela
    - value: outro
      label: Outro
  - field_name: estado
    label: Estado
    required: 'true'
    help_text: Unidade da Federação, se no Brasil.
    preset: select
    choices:
    - value: vazio
      label: " "
    - value: todos
      label: Todos
    - value: AC
      label: Acre
    - value: AL
      label: Alagoas
    - value: AP
      label: Amapá
    - value: AM
      label: Amazonas
    - value: BA
      label: Bahia
    - value: CE
      label: Ceará
    - value: DF
      label: Distrito Federal
    - value: ES
      label: Espírito Santo
    - value: GO
      label: Goiás
    - value: MA
      label: Maranhão
    - value: MT
      label: Mato Grosso
    - value: MS
      label: Mato Grosso do Sul
    - value: MG
      label: Minas Gerais
    - value: PA
      label: Pará
    - value: PB
      label: Paraíba
    - value: PR
      label: Paraná
    - value: PE
      label: Pernambuco
    - value: PI
      label: Piauí
    - value: RJ
      label: Rio de Janeiro
    - value: RN
      label: Rio Grande do Norte
    - value: RS
      label: Rio Grande do Sul
    - value: RO
      label: Rondônia
    - value: RR
      label: Roraima
    - value: SC
      label: Santa Catarina
    - value: SP
      label: São Paulo
    - value: SE
      label: Sergipe
    - value: TO
      label: Tocantins
  - field_name: idioma
    label: Idioma
    helper_text: Selecione todos que se aplicam.
    required: 'true'
    preset: multiple_select
    choices:
    - value: portugues
      label: Português
    - value: alemao
      label: Alemão
    - value: arabe
      label: Árabe
    - value: bahasa
      label: Bahasa
    - value: bengali
      label: Bengali
    - value: chines
      label: Chinês
    - value: espanhol
      label: Espanhol
    - value: frances
      label: Francês
    - value: hindi
      label: Hindi
    - value: ingles
      label: Inglês
    - value: japones
      label: Japonês
    - value: malay
      label: Malay
    - value: russo
      label: Russo
    - value: thai
      label: Thai
  - field_name: nivel_observacao
    label: Nível da observação
    required: 'true'
    preset: multiple_select
    choices:
    - value: vazio
      label: " "
    - value: placeholder_esfera
      label: _______________ESFERA
    - value: pais
      label: País
    - value: regiao
      label: Região
    - value: estado
      label: Estado
    - value: condado
      label: Condado
    - value: distrito
      label: Distrito
    - value: municipio
      label: Município
    - value: cidade
      label: Cidade
    - value: vila
      label: Vila
    - value: placeholder_imagem
      label: _______________IMAGEM
    - value: pixel
      label: Pixel
    - value: poligono
      label: Polígono
    - value: placeholder_individuo
      label: _______________INDIVÍDUO
    - value: pessoa
      label: Pessoa
    - value: domicilio
      label: Domicílio
    - value: animal
      label: Animal
    - value: placeholder_estabelecimento
      label: _______________ESTABELECIMENTO
    - value: agencia
      label: Agência
    - value: aldeia
      label: Aldeia Indígena
    - value: area_protegida
      label: Área Protegida
    - value: cartorio
      label: Cartório
    - value: empresa
      label: Empresa
    - value: escola
      label: Escola
    - value: estacao
      label: Estação
    - value: estadio
      label: Estádio
    - value: grupo_terrorista
      label: Grupo Terrorista
    - value: hospital
      label: Hospital
    - value: imovel
      label: Imóvel/Propriedade
    - value: ministerio
      label: Ministério
    - value: museu
      label: Museu
    - value: ong
      label: ONG
    - value: presidio
      label: Presídio
    - value: time
      label: Time
    - value: universidade
      label: Universidade
    - value: placeholder_politica
      label: _______________POLÍTICA
    - value: acordo_tratado
      label: Acordo/Tratado
    - value: discurso_fala
      label: Discurso/Fala
    - value: eleicao
      label: Eleição
    - value: lei
      label: Lei/Proposição/Matéria
    - value: partido
      label: Partido
    - value: placeholder_inovacao
      label: _______________INOVAÇÃO_E_COMUNICAÇÃO
    - value: artigo
      label: Artigo
    - value: citacao
      label: Citação
    - value: dominio
      label: Domínio
    - value: livro
      label: Livro
    - value: jornal
      label: Jornal
    - value: patente
      label: Patente
    - value: periodico_revista
      label: Periódico/Revista
    - value: placeholder_recursos
      label: _______________RECURSOS
    - value: convenio
      label: Convênio
    - value: licitacao
      label: Licitação/Contrato
    - value: produto
      label: Produto
    - value: transacao
      label: Transação
    - value: transferencia
      label: Transferência
    - value: placeholder_educacao
      label: _______________EDUCAÇÃO
    - value: bolsa
      label: Bolsa
    - value: prova
      label: Prova/Exame
    - value: placeholder_evento
      label: _______________EVENTOS
    - value: alerta
      label: Alerta
    - value: ataque
      label: Ataque
    - value: ato
      label: Ato
    - value: concerto_show
      label: Concerto/Show
    - value: desastre
      label: Desastre Natural
    - value: enchente
      label: Enchente/Inundação
    - value: nascimento
      label: Nascimento
    - value: pedido
      label: Pedido
    - value: obito
      label: Óbito
    - value: partida
      label: Partida
    - value: placeholder_arte
      label: _______________ARTE
    - value: album
      label: Álbum
    - value: filme_serie_clipe
      label: Filme/Série/Clipe
    - value: foto
      label: Foto
    - value: musica
      label: Música
    - value: objeto
      label: Objeto
    - value: pintura
      label: Pintura/Desenho/Ilustração
    - value: placeholder_meio_transp
      label: _______________MEIOS DE TRANSPORTE
    - value: carro_onibus
      label: Carro/Ônibus
    - value: trem
      label: Trem
    - value: aviao_helic
      label: Avião/Helicóptero
    - value: embarcacao
      label: Embarcação
    - value: placeholder_grupos
      label: _______________GRUPOS
    - value: idade
      label: Idade
    - value: raca
      label: Raça
    - value: sexo
      label: Sexo
    - value: placeholder_outros
      label: _______________OUTROS
    - value: outro
      label: Outro
  - field_name: api
    label: API
    required: 'true'
    helper_text: API são instruções e padrões de programação para acesso a um aplicativo
      ou software.
    preset: select
    choices:
    - value: vazio
      label: " "
    - value: sim
      label: Sim
    - value: nao
      label: Não
  - field_name: microdados
    label: Microdados
    required: 'true'
    preset: select
    choices:
    - value: vazio
      label: " "
    - value: sim
      label: Sim
    - value: nao
      label: Não
  - field_name: coleta
    label: Coleta
    required: 'true'
    preset: select
    choices:
    - value: vazio
      label: " "
    - value: administrativo
      label: Administrativo
    - value: amostra
      label: Amostra
    - value: censo
      label: Censo
    - value: colaborativo
      label: Colaborativo
    - value: projeto
      label: Projeto
    - value: sensoriamento_remoto
      label: Sensoriamento Remoto
    - value: outro
      label: Outro
  - field_name: ano
    label: Ano(s)
    required: 'true'
    helper_text: Selecione todos que se aplicam.
    preset: multiple_select
    choices:
    - value: vazio
      label: " "
    - value: pre_1999
      label: Pré-1999
    - value: '2000'
      label: '2000'
    - value: '2001'
      label: '2001'
    - value: '2002'
      label: '2002'
    - value: '2003'
      label: '2003'
    - value: '2004'
      label: '2004'
    - value: '2005'
      label: '2005'
    - value: '2006'
      label: '2006'
    - value: '2007'
      label: '2007'
    - value: '2008'
      label: '2008'
    - value: '2009'
      label: '2009'
    - value: '2010'
      label: '2010'
    - value: '2011'
      label: '2011'
    - value: '2012'
      label: '2012'
    - value: '2013'
      label: '2013'
    - value: '2014'
      label: '2014'
    - value: '2015'
      label: '2015'
    - value: '2016'
      label: '2016'
    - value: '2017'
      label: '2017'
    - value: '2018'
      label: '2018'
    - value: '2019'
      label: '2019'
    - value: '2020'
      label: '2020'
    - value: atual
      label: Atual
  - field_name: periodicidade
    label: Periodicidade
    helper_text: Pode ser aproximado.
    required: 'true'
    preset: select
    choices:
    - value: vazio
      label: " "
    - value: sem_atualizacao
      label: Sem Atualização
    - value: dia
      label: Dia
    - value: semana
      label: Semana
    - value: mes
      label: Mês
    - value: trimestre
      label: Trimestre
    - value: semestre
      label: Semestre
    - value: ano
      label: 1 Ano
    - value: dois_anos
      label: 2 Anos
    - value: tres_anos
      label: 3 Anos
    - value: quatro_anos
      label: 4 Anos
    - value: cinco_anos
      label: 5 Anos
    - value: dez_anos
      label: 10 Anos
    - value: recorrente
      label: Recorrente
    - value: outro
      label: Outro
  - field_name: gratis
    label: Grátis
    required: 'true'
    preset: select
    choices:
    - value: sim
      label: Sim
    - value: nao
      label: Não
  - field_name: registro
    label: Registro
    help_text: É necessário registrar um usuário para baixar os dados?
    required: 'true'
    preset: select
    choices:
    - value: nao
      label: Não
    - value: sim
      label: Sim
  - field_name: disponibilidade
    label: Disponibilidade
    required: 'true'
    preset: select
    choices:
    - value: online
      label: Online
    - value: correio
      label: Correio
    - value: presencial
      label: Presencial
  - field_name: ip_brasileiro
    label: IP brasileiro
    help_text: É necessário um IP brasileiro para acessar?
    required: 'true'
    preset: select
    choices:
    - value: nao
      label: Não
    - value: sim
      label: Sim
  - field_name: url
    label: Fonte
    form_placeholder: 'ex.: http://example.com/dataset'
    display_property: foaf:homepage
    display_snippet: link.html
  - field_name: versao
    label: Versão
    validators: ignore_missing unicode package_version_validator
    form_placeholder: 'ex.: 1.0'
  - field_name: autor
    label: Autor
    form_placeholder: 'ex.: Joe Bloggs'
    display_property: dc:creator
  - field_name: autor_email
    label: Email Autor
    form_placeholder: 'ex.: joe@example.com'
    display_property: dc:creator
    display_snippet: email.html
    display_email_name_field: author
  - field_name: mantenedor
    label: Mantenedor
    form_placeholder: 'ex.: Joe Bloggs'
    display_property: dc:contributor
  - field_name: mantenedor_email
    label: Email Mantenedor
    form_placeholder: 'ex.: joe@example.com'
    display_property: dc:contributor
    display_snippet: email.html
    display_email_name_field: maintainer
  - field_name: download_type
    label: Tipo de Download
    help_text: Qual a forma de acessar o dado em si
    required: 'true'
    preset: select
    choices:
    - value: Link Externo
      label: Link Externo
    - value: BD Mais
      label: BD Mais
resource_fields:
  - field_name: url
    label: URL
    required: 'true'
    preset: resource_url_upload
  - field_name: name
    label: Nome
    required: 'true'
    form_placeholder: 'ex.: Baixar, Visualizar'
  - field_name: descricao
    label: Descrição
    form_snippet: markdown.html
    form_placeholder: Descrição do recurso
  - field_name: formato
    label: Formato
    preset: resource_format_autocomplete
  - field_name: resource_type
    label: Tipo do Recurso
    preset: select
    choices:
    - value: bdm_table
      label: Tabela BD+
    - value: external_link
      label: Link Externo
    - value: lai_request
      label: Pedido LAI
    required: 'true'
  - field_name: is_bdm
    label: BD+
    preset: multiple_checkbox
    choices:
    - value: BD+
      label: BD+

# BDM
  - field_name: bdm_file_size
    label: bdm_file_size
    form_placeholder: markdown.html
    validators: only_on_types(bdm_table) # required_on_types(bdm_table)

# LINK EXTERNO